### ISSUE TITLE
[FEATURE] [MC-VERSION] Short description of the feature

### ISSUE THREAD

**Issue by Fall4573** [Exopandora/ShoulderSurfing#107]
Heyy just a real quick question/request. Im wondering how can I make the camera go even further back, the reason I ask is simple, the valkyrie skies mod lets you make custom ships and boats, for ease of visibility on where you're going especially for larger ships.

efforts I've made to get this result, changed config files, haven't been able to figure out what i should change to do this

what i got right now.
![Minecraft 1 12 2 2_5_2023 4_27_33 AM](https://user-images.githubusercontent.com/119358240/216811443-2b6be916-4808-42ff-809b-a98e006a846c.png)

the perspective im trying to at least get close to
![Minecraft 1 12 2 2_5_2023 4_29_47 AM](https://user-images.githubusercontent.com/119358240/216811580-142e2dbb-9c0a-484e-8b9b-06954396c15b.png)

**Comment by Exopandora** [comment]
In `.../.minecraft/config/shouldersurfing.toml` set `perspective.offset.limits.unlimited_offset_z` to `true`. Such that the section of the config file will look as follows:
```toml
[perspective.offset.limits]
#Whether or not z-offset adjustment has limits
unlimited_offset_z = true
#Whether or not y-offset adjustment has limits
unlimited_offset_y = false
#Whether or not x-offset adjustment has limits
unlimited_offset_x = false
```
If you have any fruther questions, feel free to leave another comment in this issue.
