### ISSUE TITLE
[Question] How to disable horizontal camera movement?

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [Exopandora/ShoulderSurfing#134]
### Description

Hello!
Since the latest update which reworked how camera position is managed with occlusions, many of our play community have motion sickness due to the wild horizontal camera movement.
This is particularly noticable in tight spaces such as moving around in villages.

Is there a way to configure the mod how it behaved before 2.5?
Can you give some recommendation on how to reduce/disable horizontal camera movement?

Using ShoulderSurfing-Fabric-1.20.1-2.5.jar

**Comment by Exopandora** [comment]
Thanks for the feedback! You can set `camera_transition_speed` to a low value (i.e. 0.05) to slow down the transition speed. I will also add an option to disable this feature entirely in the next update (probably this weekend).

**Comment by Exopandora** [comment]
A new version (2.6) is available for download. You can disable horizontal camera movement with the following settings:
```toml
dynamically_adjust_offsets = false
center_camera_when_looking_down_angle = 0.0
center_camera_when_climbing = false
```
