### ISSUE TITLE
[Invisible Crosshair And Sliding Crosshair] [1.20.1] Sliding Crosshairs

### ISSUE THREAD

**Issue by Fyoncle** [Exopandora/ShoulderSurfing#158]
### Description

It is an glitch that making your crosshair invisible in F5 defaults, and while in shoulder surfing mode your crosshair will slide right to left in your scenes and makes it unstable to control

### Steps to Reproduce

1. Press F3 Just 3 Times
2. Move Your Crosshair Right To Left
3. Also Invisible Crosshairs On Default F3 Which is first and second.

### Expected Behavior

I wanted crosshairs back and not sliding standing still shoulder surfing "LIKE BEFORE THE UPDATE THAT IS BREAKED IT"

### Game Logs

There's no obvious glitches in the log at all, try it for yourself and its just a visual glitch.

**Comment by Exopandora** [comment]
This looks like a configuration issue. The configuration file can be found in `.../.minecraft/config/shouldersurfing.toml`.
There, you can set the visibility for each perspective individually:
```toml
[crosshair.visibility]
#Crosshair visibility for first_person.
#Allowed Values: ALWAYS, NEVER, WHEN_AIMING, WHEN_IN_RANGE, WHEN_AIMING_OR_IN_RANGE
first_person = "ALWAYS"
#Crosshair visibility for shoulder_surfing.
#Allowed Values: ALWAYS, NEVER, WHEN_AIMING, WHEN_IN_RANGE, WHEN_AIMING_OR_IN_RANGE
shoulder_surfing = "ALWAYS"
#Crosshair visibility for third_person_back.
#Allowed Values: ALWAYS, NEVER, WHEN_AIMING, WHEN_IN_RANGE, WHEN_AIMING_OR_IN_RANGE
third_person_back = "NEVER"
#Crosshair visibility for third_person_front.
#Allowed Values: ALWAYS, NEVER, WHEN_AIMING, WHEN_IN_RANGE, WHEN_AIMING_OR_IN_RANGE
third_person_front = "NEVER"
```

If you do not want the camera moving left to right, depending on space constraints, you can either set `camera_transition_speed_multiplier` to `1.0` or `dynamically_adjust_offsets` to `false`.
