### ISSUE TITLE
Camera movement is incorrect

### ISSUE THREAD

**Issue by ThatLittleCrab** [Exopandora/ShoulderSurfing#238]
### Description

When using shoulder surfing, instead of the camera turning with the head, it rotates around the head in a sphere

It can slightly through walls if pushed hard enough. It's funny but the mod just doesn't work.
The following images show random positions from the mouse controlled camera.

![image](https://github.com/user-attachments/assets/216ea768-3e6a-49bf-b90a-da25e0273fcc)
![image](https://github.com/user-attachments/assets/753605de-68a7-446a-8bdb-a60658df98e9)
![image](https://github.com/user-attachments/assets/6e29aa8f-669c-494e-9b4b-bdbab3207992)
![image](https://github.com/user-attachments/assets/7926254a-8a94-4873-b23a-975a343e868e)

### Steps to Reproduce

Simply turning on the perspective option.

### Minecraft version

1.20.1 and Forge 47.2.20

### Game Logs

https://mclo.gs/bqGJNfW

**Comment by Exopandora** [comment]
> When using shoulder surfing, instead of the camera turning with the head, it rotates around the head in a sphere

The logs suggest that you updated Shoulder Surfing Reloaded from version 2.9.6 to 4.3.0. Since version 3.0.0 the camera rotation is independent of the rotation of the player. If you do not like this, you can still revert to the old behavior by setting `decoupled_camera` to `false` in the config file ("shouldersurfing-client.toml").

> It can slightly through walls if pushed hard enough.

I cannot reproduce this locally. Does the clipping also happen without any other mods installed? If not, please try to figure out what other mod is causing the issue and open a [new compatibility issue](https://github.com/Exopandora/ShoulderSurfing/issues/new?assignees=&labels=compatibility&projects=&template=compatibility.yaml&title=Incompatible+with+MOD).

**Comment by kappagaren58** [comment]
I feel like this is a problem between shoulder surfing and better third person because im having the same problem and the decoupled camera setting makes every movement key go straight to forward.

**Comment by Exopandora** [comment]
> I feel like this is a problem between shoulder surfing and better third person because im having the same problem and the decoupled camera setting makes every movement key go straight to forward.

Thanks for the pointer! Please uninstall Better Third Person, it is not compatible with Shoulder Surfing Reloaded as of version 3.0.0. For details, please look [here](https://github.com/Exopandora/ShoulderSurfing/issues/215#issuecomment-2179129974).

Note that it will not behave exactly as SSR 2.9.6 + BTP used to, as there are many new features that should make it easier to play in third person. I suggest starting the game with just SSR installed and to give it a shot. If you insist on having almost exactly the same experience, you need to make the following changes to the config file:

<details>
  <summary>shouldersurfing-client.toml</summary>
  
  ```toml
  [player]
      #Whether the x-rot of the player should follow the camera x-rot. This config option only applies when camera is decoupled.
      player_x_rot_follows_camera = true
      #Whether the y-rot of the player should follow the camera y-rot. This config option only applies when camera is decoupled.
      player_y_rot_follows_camera = true
      #The maximum angle to which the player y-rot follows the camera y-rot. This config option only applies when player y-rot follows camera option is enabled.
      #Range: 0.0 ~ 180.0
      player_y_rot_follow_angle_limit = 65.0

      [player.turning]
          #Whether to turn the player when attacking. This config option only applies when camera is decoupled.
          #Allowed Values: ALWAYS, NEVER, REQUIRES_TARGET
          when_attacking = "NEVER"
          #Whether to turn the player when interacting with blocks. This config option only applies when camera is decoupled.
          #Allowed Values: ALWAYS, NEVER, REQUIRES_TARGET
          when_interacting = "NEVER"
          #Whether to turn the player when picking blocks or entities. This config option only applies when camera is decoupled.
          #Allowed Values: ALWAYS, NEVER, REQUIRES_TARGET
          when_picking = "NEVER"
          #Whether to turn the player when using an item. This config option only applies when camera is decoupled.
          #Allowed Values: ALWAYS, NEVER, REQUIRES_TARGET
          when_using_item = "NEVER"
          #The time in ticks the player will remain turned after the interaction has ended. Set to 0 to disable. This config option only applies when camera is decoupled.
          #Range: > 0
          turning_lock_time = 40

  [crosshair]
      #Crosshair type to use for shoulder surfing.
      #Allowed Values: ADAPTIVE, DYNAMIC, STATIC, STATIC_WITH_1PP, DYNAMIC_WITH_1PP
      crosshair_type = "ADAPTIVE"

  [object_picker]
      [object_picker.pick_vector]
          #The vector direction of the raytrace when picking objects. This config option only applies when using the dynamic crosshair.
          #Allowed Values: PLAYER, CAMERA
          pick_vector = "PLAYER"
  ```
</details>
