### ISSUE TITLE
Crosshair isn't visible

### ISSUE THREAD

**Issue by Big-Tar** [Exopandora/ShoulderSurfing#265]
### Description

Crosshair doesn't stay visible when static. Crosshair fades in and out based on if block is close or not. 

### Steps to Reproduce

1.21.1 latest version. 
Default configuration. 

### Minecraft version

1.21.1

### Game Logs

latest.log

### Additional Information

I can't figure out how to disable it or find any documentation on this.

**Comment by Exopandora** [comment]
The only options that change the visibility of the crosshair are `crosshair.visibility`, which default to `ALWAYS` or `NEVER`:
```toml
[crosshair]
	[crosshair.visibility]
		#Crosshair visibility for first person.
		#Allowed Values: ALWAYS, NEVER, WHEN_AIMING, WHEN_IN_RANGE, WHEN_AIMING_OR_IN_RANGE
		first_person = "ALWAYS"
		#Crosshair visibility for shoulder surfing.
		#Allowed Values: ALWAYS, NEVER, WHEN_AIMING, WHEN_IN_RANGE, WHEN_AIMING_OR_IN_RANGE
		shoulder_surfing = "ALWAYS"
		#Crosshair visibility for third person back.
		#Allowed Values: ALWAYS, NEVER, WHEN_AIMING, WHEN_IN_RANGE, WHEN_AIMING_OR_IN_RANGE
		third_person_back = "NEVER"
		#Crosshair visibility for third person front.
		#Allowed Values: ALWAYS, NEVER, WHEN_AIMING, WHEN_IN_RANGE, WHEN_AIMING_OR_IN_RANGE
		third_person_front = "NEVER"
```

Unfortunately, I cannot help you any further, since no log file was provided. I'm assuming that you installed another mod that changes the crosshair.
